### ISSUE TITLE
Базовые изменения в стандартном приложении Xamarin Evolve

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#1]
Наше приложение должно отличаться от исходного [Xamarin Evolve](https://github.com/xamarinhq/app-evolve). Его внешний вид должен быть стилизирован под бренд DotNetRu. А поведение адаптированно под формат ежемесячных митапов.

- [x] Переименовать приложение в «DotNetRu App»
- [x] Использовать в качестве логотипа картинку [dotnetru-squared-logo](https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/dotnetru-squared-logo)
- [x] Изменить везде светло-фиолетовый цвет на наш тёмно-фиолетовый: [#68217A](http://www.colorhexa.com/68217a)
- [x] Убрать *Evolve Feed → Upcoming Favorites*
- [x] Изменить *Evolve Feed → Social* теги на *#SpbDotNet* и *#MskDotNet*
- [x] Убрать страницу *Sessions*
- [x] Переименовать *Events* в *Meetups* (*Встречи*)
- [x] Убрать страницу *Mini-Hacks*
- [x] Переименовать *Sponsors* в *Friends* (*Друзья*)
- [x] Убрать страницу *Evaluations*
- [x] Убрать страницу *Floor maps*
- [x] Убрать страницу *Conference Info*
- [x] Удалить *Wi Fi*
- [x] Удалить *Conduct*
- [x] Удалить *Venue*
- [x] Убрать из *Settings* упоминания о *Xamarin Account*. Пока у нас не будет никакой авторизации

**Comment by AnatolyKulakov** [comment]
Заменил картинку на _dotnetru-squared-logo_

**Comment by pfedotovsky** [comment]
All changes are done, let's do further updates under separate issues
