### ISSUE TITLE
Добавить сбор статистики использования

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#10]
Необходимо добавить в приложение сбор статистики использования.

Необходимо выбрать подходящего провайдера. Например:

- HockeyApp
- Xamarin Mobile Center

Главное требование — это наличие бесплатного плана с подходящими для наших потребностей условиями.

**Comment by pfedotovsky** [comment]
Сделаю интеграцию с Visual Studio App Center (https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/Xamarin)

**Comment by AnatolyKulakov** [comment]
@pfedotovsky что у них с тарифами?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov пока все бесплатно :)

"Visual Studio App Center offers both a generous free tier as well as paid tier options, paid through an Azure subscription. The free tier includes:
Unlimited apps, unlimited orgs, and unlimited teams.
Crashes and Analytics completely free"
