### ISSUE TITLE
Открывать сайт DotNet.Ru без Reader mode

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#112]
Сейчас на странице About, при клике на картинку с логотипом DotNet.Ru, открывается соответствующий сайт. Но он открывается в [Reader mode](https://www.imore.com/how-use-reader-view-safari-iphone-and-ipad). Что приводит к полной не работоспособности сайта и потери некоторого значимого контента.

Необходимо открывать сайт DotNet.Ru без Read mode.

**Comment by pfedotovsky** [comment]
Fixed in version 1.4.0
