### ISSUE TITLE
Обновлять базу данных Audit'а

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#12]
Приложение должно распространяться со статической версией Audit'а согласно #2.

Эту базу необходимо периодически обновлять. Приложение должно загружать базу Audit'а c GitHub'а (с использованием всех его CDN'ов и возможностей определять только изменившиеся файлы). Если Репозиторий не доступен, то приложение должно работать с последней известной версией базы.

Загрузка обновлений не должна замедлять время старта приложения и проходить в фоне.

**Comment by AnatolyKulakov** [comment]
По результатам исследования, описал способ [Обнаружения изменений Аудита](https://github.com/DotNetRu/Audit/wiki/Find-Audit-changes).

**Comment by pfedotovsky** [comment]
Сделано
