### ISSUE TITLE
App Center Monitoring: только для Release версии

### ISSUE THREAD

**Issue by pfedotovsky** [DotNetRu/App#124]
Сейчас App Center мониторит все сессии, включая Debug, что искажает статистику.
Мониторинг должен быть включен только для Release

**Comment by AnatolyKulakov** [comment]
А тесты в AppCenter'е проходят наверняка в Release режиме? Их тоже быть не должно. Должны быть только настоящие пользователи, больше никого.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov Тесты только в Release - и они нужны. Иначе как убедиться, что приложение и правда стартует?

**Comment by AnatolyKulakov** [comment]
Тесты нужны. Убедиться что всё стартует и работает можно по зелёному индикатору самих тестов. Но в метриках они никак отсвечивать не должны.  Метрики только для настоящих пользователей!

**Comment by VetaLioSTV** [comment]
Для релиза и дебага делается два разных билда,которые заливаются отдельно в аппцентр(и соответственно имеют разные ключи).

**Comment by pfedotovsky** [comment]
@VetaLioSTV У нас в App Center только Release билды, которые потом заливаются в Google Play/App Store. Мониторинг нужен только реальных пользователей приложения, то есть исключая запуски не из магазинов.
