### ISSUE TITLE
Увеличить разнообразие Докладчиков на снимке

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#125]
Сейчас на с снимке страницы Докладчиков (Speakers) во всех магазинах красуется список, в котором 4 из 6 человек являются представителями одной фирмы. Это может навести наблюдателя на неверные мысли об умышленном занижении разнообразия (diversity) докладчиков и дискриминации по брендовому признаку.

Необходимо заменить снимок на более политкорректный. Демонстрирующий наше толерантное отношение ко спикерам из любой фирмы.

**Comment by pfedotovsky** [comment]
Сделано в релизе 1.5.0 (уже в магазинах)

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , в Google Play всё ещё 4 из одной фирмы. Т.е. ничего не поменялось.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov да, действительно, забыл обновить скриншоты для англоязычной версии.
Теперь везде должны быть новые.
