### ISSUE TITLE
Увеличить размер новостной ленты

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#131]
Сейчас на вкладке "Новости" (News) самая старая новость датирована примерно "20 дней назад". Так как мы публикуем мало новостей, этого не достаточно для полноценного ознакомления с нашей деятельностью.

Необходимо увеличить лимит новостей хотя бы раза в 3.

**Comment by vadlit** [comment]
Хочу попробовать сделать

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , проверь пожалуйста актуальность задачи

**Comment by pfedotovsky** [comment]
Количество твитов было увеличено, поэтому уже неактуально.
