### ISSUE TITLE
Добавить в профиль Докладчика ссылку на GitHub

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#147]
Сейчас на вкладке докладчика (Speaker) есть ссылки на его контакты (блог, Твитер, Хабр и т.д.).

Необходимо поддержать новый профиль - аккаунт на GitHub (DotNetRu/Audit#31). Сия ссылка должна отображаться на вкладке Докладчика наряду со всеми остальными.

**Comment by vadlit** [comment]
Обновил PR - https://github.com/DotNetRu/App/pull/219
Два других PR больше не нужны.

**Comment by pfedotovsky** [comment]
Можно смотреть в версии 2.1.0
