### ISSUE TITLE
Выделить имя докладчика

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#151]
Сейчас на странице Докладчика (Speaker), на фотографии, в левом нижнем углу отображается имя и фамилия персонажа. Так как у надписи белый цвет она плохо видна на светлом фоне некоторых фотографий.

Необходимо выделить имя и фамилию Докладчика, так чтобы они всегда были отчётливо видны на любой фотографии. Для цветового выделения (подложка, свечение, тень) можно использовать [один из наших фоновых цветов](https://github.com/DotNetRu/DotNetRu.github.io/wiki/Corporate-colours).

![photo5274159607322880151](https://user-images.githubusercontent.com/11032050/37494226-f998596c-28b8-11e8-80ae-782089c90634.jpg)

**Comment by vadlit** [comment]
https://github.com/DotNetRu/App/pull/218

![image](https://user-images.githubusercontent.com/5470737/51799582-ba8d2700-2233-11e9-9741-f9c5f81f7f26.png)

**Comment by AnatolyKulakov** [comment]
@vadlit Как-то слишком броско. Надо подобрать более эргономичное решение.

**Comment by AnatolyKulakov** [comment]
Хорошо, попробую нарисовать

**Comment by AnatolyKulakov** [comment]
- Цвета: #704679, #af64c2 (те же, только насыщенность меньше) с прозрачностью
- Выравнивание шрифта по центру
- Отступы фона от основного текста
- Фигурные края фона
- Нужно проверить длинные Имена. Они должны переноситься на две строки, если не влезают. Если даже на две не влезают (для компаний это возможно), то можно обрезать
- Нужно не забыть, что Компания может отсутствовать

![label](https://user-images.githubusercontent.com/11032050/51803054-86305f80-2261-11e9-8b77-8486376d10e3.jpg)

**Comment by vadlit** [comment]
Выглядит классно, переделаю

**Comment by AnatolyKulakov** [comment]
Шикарно :+1:

**Comment by AnatolyKulakov** [comment]
Можно даже чуть поменьше прозрачности. В макете фон темнее.
