### ISSUE TITLE
Добавить ссылки на другие части Доклада

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#152]
У некоторых докладов (Talk) есть ссылки на другие их части (`SeeAlsoTalkIds`). Например:

[Теория и практика .NET-бенчмаркинга (часть 1 из 2)](https://github.com/DotNetRu/Audit/blob/master/db/talks/Theory-and-practice-of-NET-benchmarking-1.xml)
[Теория и практика .NET-бенчмаркинга (часть 2 из 2)](https://github.com/DotNetRu/Audit/blob/master/db/talks/Theory-and-practice-of-NET-benchmarking-2.xml)

Необходимо на страницу доклада, после секции "Аннотация", добавить секцию "См. также" ("See also") с перечислением всех ссылок на другие части доклада. Ссылка должна открывать окно соответствующего выступления. Порядок элементов должен совпадать с порядком в Audit файле.

**Comment by vadlit** [comment]
Попробую свои силы

**Comment by vadlit** [comment]
Готово.
https://github.com/DotNetRu/App/pull/215 - основные изменения
https://github.com/pfedotovsky/DotNetRu.RealmGenerator/pull/3 - изменения в приложении, с помощью которого я сгенерил realm
https://github.com/pfedotovsky/dotnetru-backend/pull/4 - изменения в бэкенде, который выдает обновленный контент

Считаю, что все эти репы надо объединять в один солюшн и использовать в них общие проекты. Т.к. при текущей реализации имеем:
а) копипасту в трех солюшнах
б) много головной боли для достаточно стандартной задачки вида "добавить такое-то поле"
в) неочевидный скоуп изменений, которые надо провести, для новичков вроде меня

И еще - я не знаю как это проверить. Точнее я проверил всё (на виртуальном устройстве) на старой версии UpdateService, который не работал с Azure. А на новой версии я не могу проверить, т.к. для этого надо обновить код в Azure, у меня прав на это наверняка нет. В общем проблемы тестовой среды.

**Comment by AnatolyKulakov** [comment]
Согласен, надо объединять репозитории.
@pfedotovsky , что думаешь?

**Comment by pfedotovsky** [comment]
@vadlit, спасибо!

Я переделаю генерацию Realm в Azure и добавлю в общий репозиторий, чтобы было удобнее. 

Про тестовую среду - Azure Function можно запустить как обычное консольное приложение и проверить локально. Правда ссылка на API сейчас захардкожена, нужно ее вынести в конфиг.

**Comment by unchase** [comment]
Можно закрывать задачу, так как она выполнена.
По поводу объединения репозиториев - лучше вынести в отдельную задачу и определиться, что именно и как объединять.

**Comment by AnatolyKulakov** [comment]
Объединение кажется тоже сделали.
