### ISSUE TITLE
Удалять календарь приложения вместе с приложением

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#19]
После установки приложения Xamarin Evolve у меня в системе создался отдельный календарь. В нём сохранялись встречи. После удаления приложения, календарь остался в системе.

Необходимо удалять календарь приложения вместе с самим приложением.

Воспроизвёл на _Windows Mobile 10_

**Comment by pfedotovsky** [comment]
Проверить на iOS и Android

**Comment by AnatolyKulakov** [comment]
Да, закрывай
