### ISSUE TITLE
Изменить порядок сортировки Докладчиков

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#192]
Сейчас на странице Speakers список Докладчиков начинается с Английских имён. Крайне возмутительное решение для приложения, нацеленного на Российский рынок. Это явная дискриминация по национальному признаку.

Необходимо сортировать сначала Русские имена, а затем Латинские.

**Comment by akiriushin** [comment]
Очень странная задача, прежде всего своей формулировкой

**Comment by vadlit** [comment]
Попробую сделать

**Comment by vadlit** [comment]
Pushing to git@github.com:DotNetRu/App.git
ERROR: Permission to DotNetRu/App.git denied to vadlit.
fatal: Could not read from remote repository.

**Comment by vadlit** [comment]
Без SSH тоже не дает запушить

**Comment by AnatolyKulakov** [comment]
На GitHub'е необходимо вносить изменения с помощью Pull Request'ов. В статье "[Как сделать свой первый Pull Request](https://rustycrate.ru/руководства/2016/03/07/contributing.html)" подробнее описан процесс.

**Comment by vadlit** [comment]
Понял, сделаю через форк. Пытался напрямую фича-бранчу создать
