### ISSUE TITLE
Падает открытие спикера Айрат Худайгулов

### ISSUE THREAD

**Issue by vadlit** [DotNetRu/App#206]
При открытии карточки спикера Айрат Худайгулов приложение закрывается с ошибкой. Эксепшен UnhandledException без стектрейса. Повторяется стабильно и на устройстве, и в эмуляторе. На других карточках не повторяется. От порядка спикеров точно не зависит (проверил, переместив его изменениями в коде подальше).

## Ожидаемое поведение
Карточка открывается без ошибок.

## Технические детали
* Версия приложения - 1.2.0
* Платформа (вместе с версией ОС): 
  * [ ] iOS 
  * [x] Android 8.0

**Comment by bruce-willis** [comment]
Проблема в его докладах, так как если на время убрать доклады:
```cs
public IEnumerable<TalkModel> Talks => new List<TalkModel>();//this.SpeakerModel.Talks;
```
в файле `SpeakerDetailsViewModel.cs`, то при открытии не падает.
нужно копать дальше

**Comment by AnatolyKulakov** [comment]
Скорее всего это произошло из-за переименования доклада. Посмотрите DotNetRu/Audit#72

**Comment by pfedotovsky** [comment]
@AnatolyKulakov @bruce-willis я выпущу новую версию с уже готовой базой. В дальнейшем улучшим синхронизацию данных через Azure Functions

**Comment by pfedotovsky** [comment]
Fixed
