### ISSUE TITLE
Некорректно отображается продолжительность встречи MskDotNet №25

### ISSUE THREAD

**Issue by Taritsyn** [DotNetRu/App#209]
На карточке встречи MskDotNet №25 некорректно отображается временная продолжительность. В [XML-файле](https://github.com/DotNetRu/Audit/blob/master/db/meetups/MskDotNet-25.xml) данные указаны корректно. На карточках других встреч таких проблем не обнаружил.

## Ожидаемое поведение
19:00-21:30

## Текущее поведение
20:30-20:00

## Как воспроизвести
Открыть карточку встречи MskDotNet №25.

## Технические детали
* Версия приложения - 1.2.0
* Платформа (вместе с версией ОС): 
  * [ ] iOS 
  * [x] Android (эмулятор BlueStacks 4.31.70.3401)

## Скриншоты
<img src="https://i.imgur.com/RGSHNT0.png"/>

**Comment by vadlit** [comment]
Смотрю на реальном устройстве Android (версия приложения 1.2.0) - и проблема не повторяется (написано 19:00 - 21:30)
Воспроизводится ли проблема у вас сейчас? Повторяется ли она на реальном устройстве? Какая у вас временная зона выбрана в настройках телефона?

**Comment by Taritsyn** [comment]
Здравствуйте, Вадим!

На реальном устройстве не проверял. На эмуляторе проблема еще сохранялась. Но сейчас я попробовал переустановить приложение и это помогло: теперь корректно отображается продолжительность и доклады отсортированы в правильном порядке. Возможно проблема была в синхронизации данных.

Спасибо за помощь!
