### ISSUE TITLE
Улучшить качество аватаров в ленте Твиттера

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#211]
## Ожидаемое поведение
Аватары в ленте Твиттера отображаются с качеством не хуже чем это же сообщение в браузере.

## Текущее поведение
Аватары в ленте Твиттера отображаются с худшим качеством (размытые, нечёткие, пережатые) чем это же сообщение в браузере.

## Как воспроизвести
1. Открыть ленту Твиттера в приложении
2.  Отрыть любое сообщение в браузере
3. Сравнить качество картинки аваторов

## Технические детали
* Версия приложения - 1.2.0
* Платформа (вместе с версией ОС): 
  * [ ] iOS 
  * [ ] Android

## Скриншоты
Я вырезал аватары и поставил их рядом для более очевидного различия. Слева картинки из приложения. Справа тоже сообщение но web-версия.

![bug](https://user-images.githubusercontent.com/11032050/50312974-06bdac80-04bb-11e9-9c05-1d36ade43fa6.png)

**Comment by vadlit** [comment]
Кстати на сплэш-экране тоже картинка размытая. Но это можно решить только предоставлением картинки для сплэша в более высоком разрешении (там сейчас она достаточно маленькая)

**Comment by AnatolyKulakov** [comment]
Да, там было бы тоже неплохо починить. Качества полно:
https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/dotnetru-squared-logo
Есть 5000px на 5000px и даже в векторе. Выбирайте на любой вкус :)

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , а почему репозиторий бекенда у тебя в локальном аккаунте? Не хочешь ли его в Сообщество перенести?

**Comment by vadlit** [comment]
> Да, там было бы тоже неплохо починить. Качества полно:
> https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/dotnetru-squared-logo
> Есть 5000px на 5000px и даже в векторе. Выбирайте на любой вкус :)

Оказалось, что со сплэшем не всё так просто. По идее всё написано и так правильно, отчего не работает - пока не понял. Надо поиграться со свойствами scaleType, gravity, а возможно и еще с чем-то.
Лучше бы отдельную задачу, если актуально.

**Comment by AnatolyKulakov** [comment]
Готово #213
