### ISSUE TITLE
Добавить Омск

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#216]
Необходимо добавить в список активных сообществ (About) Омск:

Город: Омск
Сообщество: OmsDotNet
Ссылка: https://vk.com/OmsDotNet
Логотип: https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/omsdotnet-squared-logo

**Comment by vadlit** [comment]
Готово - https://github.com/DotNetRu/App/pull/228
При этом в рамках задачи https://github.com/DotNetRu/App/issues/6 переделываю, чтобы более гибкий механизм был (прямо из аудита и брать информацию о сообществах, там почти всё есть)

**Comment by AnatolyKulakov** [comment]
@vadlit Это было бы просто замечательно 👍
