### ISSUE TITLE
Надо чтобы по нажатии на номер версии в настройках, она копировалась в буфер

### ISSUE THREAD

**Issue by vadlit** [DotNetRu/App#225]
Надо чтобы по нажатии на номер версии в настройках, она копировалась в буфер.

А то репортить неудобно

**Comment by AnatolyKulakov** [comment]
И при этом желательно как-то визуально индицировать что оно скопировалось. Ибо если будет происходить в тихую, то будет не понятно, что что-то случилось.

**Comment by vadlit** [comment]
PR: https://github.com/DotNetRu/App/pull/226

**Comment by vadlit** [comment]
@pfedotovsky

**Comment by unchase** [comment]
Можно закрывать.
