### ISSUE TITLE
Не отображаются изменения в Аудите при смене даты Встречи

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#234]
Не отображаются изменения в Аудите.

1. Мы добавили новую встречу сообщества Omsk-2 (DotNetRu/Audit@2d1ca0ad75fb5108452473f85ea4c602dcdbcead) с датой проведения мероприятия 2019-02-07 (это была неверная дата)
2. Затем мы изменили дату на 2019-04-18 (DotNetRu/Audit@c016f2db3f62b1323dc87a1d5be5c4e38d7b08d2).

Эти изменения не отображаются в приложении. Я по прежнему вижу Omsk-2, который 7-го февраля.

Любые изменения Аудита должны отображаться в приложении.

**Comment by vadlit** [comment]
https://github.com/DotNetRu/App/pull/239
Было две проблемы, обе поправил:
- Основная: изменения по сессиям в принципе не умели нормально прочитываться
- Минорная: любые изменения было видно не сразу, а лишь после переключения по вкладкам.

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , давай это выпустим побыстрее?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov выпущено в версии 2.1.0
