### ISSUE TITLE
Для круглого стола нет фотографии

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#235]
Для события "Встреча SpbDotNet №43", на форме встречи, секции Talk нет никакой фотографии для круглого стола.

Наверное собирать какую-то общую панораму сложно и бесперспективно. Поэтому предлагаю для докладов, где больше одного человека здесь рисовать логотип сообщества, в рамках которого прошла встреча.

**Comment by unchase** [comment]
Исправлено в PR #267

**Comment by unchase** [comment]
Можно закрывать.
