### ISSUE TITLE
Не влезает название круглого слота

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#236]
Для события "Встреча SpbDotNet №43", на форме встречи, секции Talk не влезает название круглого стола.

Любое название должно влезать полностью.

**Comment by unchase** [comment]
Возможно, проблема уже решена.

![124421](https://user-images.githubusercontent.com/29679226/76702706-07082000-66dd-11ea-9d73-eaa35caf9182.jpg)

**Comment by AnatolyKulakov** [comment]
Да, действительно
