### ISSUE TITLE
Не влезает имя Докладчика

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#237]
Для события "Встреча SpbDotNet №43", на форме встречи, секции Talk, из-за длинного названия, не влезло имя докладчика Кугушева.

Любое имя должно влезать при любом размере названия.

**Comment by unchase** [comment]
Возможно, проблема уже исправлена.

![124421](https://user-images.githubusercontent.com/29679226/76702689-de802600-66dc-11ea-846d-f6868f7d8b1e.jpg)
