### ISSUE TITLE
Странная секция Location

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#238]
На странице любого доклада (Talk) сейчас показывается пустая секция Location.

Необходимо выяснить когда и зачем она появилась. Если в ней должна быть какая то информация, то нужно таковую отыскать и отобразить. Если Секция появилась случайно, необходимо её удалить.

**Comment by unchase** [comment]
Насколько я могу судить, такой секции уже нет. Проблема исправлена?

**Comment by AnatolyKulakov** [comment]
Да
