### ISSUE TITLE
Приложение падает при виде Кокосы

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#241]
## Ожидаемое поведение

Приложение никогда не падает

## Текущее поведение

Приложение иногда падает

## Как воспроизвести

1. Открываем приложение
2. Переходим на вкладку Meetups
3. Открываем встречу Spb-45
4. Кликаем на доклад Конрада
5. Приложение падает

## Технические детали

* Версия приложения - 1.7.1
* Платформа (вместе с версией ОС): 
* [ ] iOS 
* [x] Android

**Comment by pfedotovsky** [comment]
Исправлено в версии 2.1.0
