### ISSUE TITLE
Добавить Нижний Новгород

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#242]
Необходимо добавить в список активных сообществ (About) Нижний Новгород:

Город: Нижний Новгород
Сообщество: NnvDotNet
Ссылка: https://vk.com/NnvDotNet
Логотип: https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/nnvdotnet-squared-logo

**Comment by pfedotovsky** [comment]
Done, please check
