### ISSUE TITLE
Не отображается логотип друга

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#243]
## Ожидаемое поведение

В форме встречи, в секции Friends должны отображаться логотипы друзей.

## Текущее поведение

Для некоторый встреч, логотип друга не отображается.

## Как воспроизвести

1. Открываем приложение
2. Вкладка "Meetups"
3. Открываем Встреча Nnv №1 (от 22 мая)
4. Видим пустую секцию Friends

## Технические детали

* Версия приложения - 1.7.1
* Платформа (вместе с версией ОС): 
  * [ ] iOS 
  * [x] Android

## Скриншоты

![Screenshot_2019-05-25-23-37-28-268_com dotnetru droid](https://user-images.githubusercontent.com/11032050/58374404-3c713080-7f46-11e9-9d1b-b1cf57470e9c.png)

**Comment by unchase** [comment]
У меня не воспроизводится. Есть еще примеры?

**Comment by AnatolyKulakov** [comment]
Сейчас всё отображается
