### ISSUE TITLE
Добавить Уфу

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#244]
Необходимо добавить в список активных сообществ (About) Уфу:

Город: Уфа
Сообщество: UfaDotNet
Ссылка: https://vk.com/UfaDotNet
Логотип: https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/ufadotnet-squared-logo

**Comment by pfedotovsky** [comment]
Done, please check
