### ISSUE TITLE
Добавить Пензу

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#247]
Необходимо добавить в список активных сообществ (About) Пензу:

Город: Пенза
Сообщество: PnzDotNet
Ссылка: https://vk.com/penzadotnet
Логотип: https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/pnzdotnet-squared-logo

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , у меня всё ещё как PnzDotNet показывается

**Comment by pfedotovsky** [comment]
Исправлено в 1.9.0, скоро будет доступно обновление в магазинах

**Comment by AnatolyKulakov** [comment]
Fixed
