### ISSUE TITLE
Отсортировать сообщества

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#250]
Сейчас на странице "About" все сообщества ("Our communities") отсортированы в случайном порядке.

Необходимо отсортировать их согласно [официальным рекомендациям](https://github.com/DotNetRu/Audit/wiki/Community-Order). Список должен начинаться с самого старшего сообщества и заканчиваться самым молодым.

**Comment by unchase** [comment]
Исправлено в PR #265

**Comment by unchase** [comment]
Можно закрывать.
