### ISSUE TITLE
Не видно Доклада у Спикера

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#254]
## Ожидаемое поведение

У докладчика отображаются его доклады.

## Текущее поведение

У некоторых докладчиков докладов не видно. Например у Chris Ryder и Stewart Ridgway.

## Как воспроизвести

1. Открываем вкладку Speakers
2. Проматываем в самый конец и находим там докладчика Stewart Ridgway
3. Открываем форму докладчика и видим, что секция с докладами уехала за экран и не видно ни одного доклада.

## Скриншоты

![image](https://user-images.githubusercontent.com/11032050/66600693-bbda6600-ebae-11e9-8e9b-9c185627e286.png)

**Comment by unchase** [comment]
У меня проблема не воспроизводится.

![123](https://user-images.githubusercontent.com/29679226/76697738-f4292780-66ab-11ea-9df7-dfdb4564bfaa.jpg)

Возможно, актуально для конкретных устройств.

**Comment by AnatolyKulakov** [comment]
Перепроверил, всё работает как надо.
Видимо, починили в другом изменении.
