### ISSUE TITLE
Нет логотипа Сообщества в докладе Елесеева

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#256]
С списке докладов у Дмитрия Елисеева отсутствует логотип Краснодара.

Хотя Краснодар есть в списке сообществ на странице About.

![image](https://user-images.githubusercontent.com/11032050/66601328-538c8400-ebb0-11e9-8403-59e6a24a26a2.png)

**Comment by unchase** [comment]
Исправлено в PR #267

**Comment by unchase** [comment]
Можно закрывать.
