### ISSUE TITLE
Не нужно показывать секцию Friends если их нет

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#257]
## Ожидаемое поведение

Если секция пустая, то показывать её не нужно.

## Текущее поведение

На форме Встречи, секция Friends отображается даже если Друзей нет.

## Как воспроизвести

1. Открыть встречу KrdDotNet №1
2. Улицезреть пустую секцию Friends

**Comment by unchase** [comment]
Исправлено в PR #271

**Comment by unchase** [comment]
Можно закрывать.
