### ISSUE TITLE
Не обновляется список Встреч

### ISSUE THREAD

**Issue by kulakovt** [DotNetRu/App#258]
## Ожидаемое поведение

После добавления новой Встречи в Аудит, она должна появляться в приложении.

## Текущее поведение

Я [добавил Spb-53](https://github.com/DotNetRu/Audit/commit/8896b2849d76aa4474813c02696cfab0dd486ff5) и в приложении Встреча не появилась :disappointed: 

## Как воспроизвести

1. Переведите свой проект на Realm
2. В течении многих лет наблюдайте, что оно перестало обновлять данные как бы вы ни старались и ни исправляли все ошибки

**Comment by pfedotovsky** [comment]
Исправлено в версии 2.1.0

**Comment by AnatolyKulakov** [comment]
Хук обновил, подождём первого обновления

**Comment by AnatolyKulakov** [comment]
Добавил слайды 3 дня назад ко встрече 58. В приложении всё-ещё без изменений.
