### ISSUE TITLE
Не открываются внешние ссылки

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#259]
## Ожидаемое поведение

При клике на ссылки ко внешним ресурсам, они открываются.

## Текущее поведение

Все ссылки переслали открываться.

## Как воспроизвести

1. Перейти на страницу Meetups
2. Открыть встречу №49
3. Открыть доклад "Брокеры..."
4. Попробовать перейти на сайт со слайдами
5. Попробовать перейти на сайт с видео
6. Открыть форму Speaker для Дмитрия
7. Попробовать перейти в его блог
8. Попробовать перейти в его Твиттер

**Comment by pfedotovsky** [comment]
@AnatolyKulakov исправлено в версии 2.1.0

**Comment by AnatolyKulakov** [comment]
Пункты 6 и 7 исправлены.
Пункты 4 и 5 - нет.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov исправлено в версии 2.1.1
