### ISSUE TITLE
Добавить Ekb

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#260]
У нас появилось новое [сообщество в Екатеринбурге](https://github.com/DotNetRu/Audit/blob/master/db/communities/EkbDotNet.xml).

Нужно добавить его к списку сообществ. Сейчас его там нет.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov готово, версия 2.1.0

**Comment by AnatolyKulakov** [comment]
У меня отображается как "EkbDotNet".
Хотелось бы видеть название города, как и остальные города.

**Comment by unchase** [comment]
Исправлено в PR #266

**Comment by unchase** [comment]
Можно закрывать.
