### ISSUE TITLE
Нет логотипов сообщества возле докладов

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#263]
## Ожидаемое поведение
Возле каждого доклада должен быть логотип сообщества, в рамках которого доклад был прочитан.

## Текущее поведение
Возле всех докладов пустой фиолетовый квадрат.

## Как воспроизвести

1. Переключиться на вкладку "Speakers"
2. Выбрать "Алексея Мерсона"
3. Прокрутить до секции "Talks"

## Технические детали
* Версия приложения - 2.1.0
* Платформа (вместе с версией ОС): Android

## Скриншоты
![image](https://user-images.githubusercontent.com/11032050/73141224-bab44280-4092-11ea-9e2a-ab9992269efb.png)

**Comment by unchase** [comment]
Исправлено в PR #267

**Comment by unchase** [comment]
Можно закрывать.
