### ISSUE TITLE
Не открывается оригинал новости

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#269]
## Ожидаемое поведение

При нажатии на новость, должен открываться её оригинальный Твит.

## Текущее поведение

При клике на новость ничего не происходит.

## Как воспроизвести

1. Открываем вкладку News
2. Кликаем по любой новости
3. Ничего не происходит (оригинальный Твит не открывается)

## Технические детали

Версия приложения - 2.1.1
Платформа - Android

**Comment by unchase** [comment]
Исправлено в PR #273

**Comment by unchase** [comment]
Можно закрывать.
