### ISSUE TITLE
Дребезжание экрана при возвращении назад

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#270]
##  Ожидаемое поведение

При возвращении назад происходит плавное переключение на предыдущий экран

## Текущее поведение

При возвращении назад происходит переключение на предыдущий экран и небольшое моргание картинки (быстрое переключение несколько раз предыдущего экрана и нового).

## Как воспроизвести

1. Открыть вкладку Meetups
2. Открыть любой Meetup
3. Открыть любого спикера
4. Нажать на стрелочку "Назад" (что в левом верхнем углу)
5. Узреть моргание экрана Спикера и Митапа
6. Нажать на стрелочку "Назад" (что в левом верхнем углу)
7. Узреть моргание экрана Митапа и Списка митапов

## Технические детали

Версия приложения - 2.1.1
Платформа - Android

**Comment by pfedotovsky** [comment]
@AnatolyKulakov это бага Xamarin.Forms, появившаяся в последних версиях.

@bruce-willis можешь добавить workaround пожалуйста?

**Comment by AnatolyKulakov** [comment]
Надо что-то придумать. Это очень раздражает. 
Бага также присутствует в текущей версии DotNext.

**Comment by unchase** [comment]
У меня проблема не воспроизводится.
Можешь прикрепить gif с иллюстрацией?

**Comment by AnatolyKulakov** [comment]
Может @pfedotovsky  уже всё починил?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov @unchase у меня воспроизводится на физическом устройстве, починю до релиза. На эмуляторе это поведение не очень заметно.
