### ISSUE TITLE
Мелкие UI доработки после первого beta тестирования

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#28]
Первое закрытое тестирование выявило необходимость мелких доработок.

## Вкладка DotNetRu News

- [x] Вкладка должна называться просто "News"
- [x] Сейчас в правом верхнем углу есть значок "Upload". Он не работает. Скорее всего он вообще здесь не нужен.
- [x] Сейчас присутствует секция Feedback с неправильной ссылкой. Она не нужна.
- [x] Сейчас присутствует секция Announcements с неправильной ссылкой. Скорее всего она не нужна.
- [x] Сейчас в ленте Твиттера не показываются Retweets, только оригинальный контент. Хотелось бы видеть такую же ленту как и на сайте Твитера т.е. с retweet'ами.

## Вкладка Speakers

- [x] Сейчас при протаскивании списка вниз происходит "подгрузка" новых данных. Наверное это лишнее

## Вкладка Speaker Info

- [x] Убрать из секции Follow ссылку на сайт фирмы работодателя

## Вкладка Meetups

- [x] Количество элементов в заголовке кажется бесполезным. Его можно убрать
- [x] Серые кружочки с датами вызывают чувство недогруженности картинок. Давайте сделаем их Фиолетовыми
- [x] Время показывается не верно. Везде "All Day" хотя при переходе к Sessions видно что время должно быть "18:00-21:00"

## Вкладка Sessions

- [x] Лучше назвать Meetup
- [x] Строка поиска здесь не нужна
- [x] Настройка Filter не нужна
- [x] Необходимо сделать какой-нибудь заголовок с названием Встречи
- [x] Список докладов необходимо вложить в секцию Talks (Доклады)
- [x] Необходимо добавить секцию Venue (Место) с адресом места проведения и возможностью посмотреть его на карте
- [x] К названиям Докладов можно добавить фотографии спикеров

## Вкладка Session Details

- [x] Должна называться Talk
- [x] Убрать секцию Leave Feedback
- [x] Убрать секцию Add to Calendar, если событие уже прошло
- [x] Переместить секцию Follow после Abstract
- [x] Переименовать секцию Session Materials в просто Materials
- [x] Переименовать Session Recording в Talk Recording
- [x] Кнопка Upload формирует текст (например в Mail) с неверными ссылками

## Вкладка Info

- [x] Пункт About this app переместить в самый конец
- [x] Пункт About this app должен входить в секцию Application Info?
- [x] Пункт Friends лучше удалить от сюда. Друзья должны быть описаны во вкладке Sessions
- [x] Первым пунктом добавить About DotNetRu. Сделать банер из логотипа и забить [статический текст из wiki](https://github.com/AnatolyKulakov/SpbDotNet/wiki)

## Вкладка Sponsor Details

- [x] Назвать Friend
- [x] Добавить логотип

## Вкладка About this app

- [x] Пересмотреть все ссылки, многие из низ ведут в заблуждение, исправить, удалить
- [x] Необходимо чтобы по версии приложения можно было найти когда и из каких текстов она была собрана. Т.е. моё приложение обновилось, а версия в нём как была "1.0.0" так и осталась. Необходим какой-то Build Number для разбора багов.

**Comment by AnatolyKulakov** [comment]
Вынес 3 не быстрых задачи отдельно

**Comment by pfedotovsky** [comment]
@AnatolyKulakov "К названиям Докладов можно добавить фотографии спикеров"
Сколько может быть спикеров у доклада? Пока я видел только максимум 2

**Comment by AnatolyKulakov** [comment]
Сколько угодно, [например пять](https://github.com/DotNetRu/Audit/blob/master/db/talks/Round-table-code-analysis.xml), если это круглый стол.
