### ISSUE TITLE
Обрезанный текст в Title у выбранных Tab'ов на русском языке

### ISSUE THREAD

**Issue by unchase** [DotNetRu/App#280]
В `TabBar` при выставленном русском языке часть текста в `Tab`'ах: _"Докладчики"_ и _"О проекте"_ обрезана из-за того, что весь текст не помещается в одну строку.

## Ожидаемое поведение
Текст в `Title` должен отображаться полностью.

## Текущее поведение
`Title` не помещается в строку, поэтому часть текста не видно.

## Как воспроизвести
1. Переключиться на русский язык в приложении (устройстве)
2. Перейти на таб _"Докладчики"_ или _"О проекте"_
3. Увидеть, что текст обрезан

## Технические детали
* Версия приложения - 2.1.1
* Платформа (вместе с версией ОС): 
  * [ ] iOS - не могу проверить
  * [x] Android

## Скриншоты
![font_size](https://user-images.githubusercontent.com/29679226/77100156-3c3aa800-6a26-11ea-8542-2d7dfc1b4930.png)

![font_size2](https://user-images.githubusercontent.com/29679226/77100162-3f359880-6a26-11ea-954a-ab65ab449baf.png)

**Comment by AnatolyKulakov** [comment]
Какие есть решения? Уменьшить шрифт?

**Comment by unchase** [comment]
> Какие есть решения? Уменьшить шрифт?

Первое, что приходит в голову. Но пока не разобрался, как это сделать для `Tab`.

**Comment by unchase** [comment]
Есть еще решение в лоб: переименовать табы: _"Докладчики"_ -> _"Спикеры"_, _"О программе"_ -> _"Инфо"_.

**Comment by AnatolyKulakov** [comment]
Переименовать можно, но только не англицизмами: _Спикеры_, _Инфо_. Хотелось бы родных аналогов.

**Comment by pfedotovsky** [comment]
Проблема в Xamarin.Forms: https://github.com/xamarin/Xamarin.Forms/issues/7713
Сейчас вроде исправили, я обновил версии пакетов AndroidX.

У меня локально обрезается только "Докладчики" на "Докладчик" (скриншоты ниже). @AnatolyKulakov насколько это критично?

@unchase можешь пожалуйста посмотреть, какое у тебя поведение на последней версии "develop" ветки?

![image](https://user-images.githubusercontent.com/13116698/77257317-8f119b00-6c84-11ea-8fc1-a3cb5409c074.png)

![image](https://user-images.githubusercontent.com/13116698/77257332-a2246b00-6c84-11ea-9654-64eb579c421d.png)

**Comment by unchase** [comment]
@pfedotovsky на устройстве (API 28) так же, как на твоих скринах выше.
На эмуляторах (API 28, 29) проблема все еще воспроизводится.

**Comment by pfedotovsky** [comment]
@unchase спасибо! У меня на эмуляторе c API 29 нет обрезаний. Ты проверяешь с Windows?

**Comment by AnatolyKulakov** [comment]
> @AnatolyKulakov насколько это критично?

Обрезание это большая кривость.

**Comment by pfedotovsky** [comment]
@unchase а скриншоты в описании задачи у тебя были с реального устройства?

**Comment by pfedotovsky** [comment]
@unchase команда Xamarin.Forms очень быстро отвечает (https://github.com/xamarin/Xamarin.Forms/issues/7713)  :)

Обновил пакет Xamarin.Google.Android.Material, теперь нет обрезания.

Можешь пожалуйста проверить, какое у тебя поведение на последней версии "develop" ветки на эмуляторе/устройстве?

<img width="775" alt="image" src="https://user-images.githubusercontent.com/13116698/77260641-672d3200-6c9a-11ea-85d9-963abf4c8628.png">

<img width="775" alt="image" src="https://user-images.githubusercontent.com/13116698/77260652-744a2100-6c9a-11ea-9ebb-c5680e5c69a0.png">

**Comment by unchase** [comment]
@pfedotovsky ответил в PR #281
