### ISSUE TITLE
Новая минорная версия приложения (release)

### ISSUE THREAD

**Issue by unchase** [DotNetRu/App#283]
Думаю, что можно выпускать новый релиз (инкрементировать минорную версию) после подтверждения всех merge request'ов.

## Технические детали
* Версия приложения - 2.2.0
* Платформа (вместе с версией ОС): 
  * [ ] iOS 
  * [ ] Android

**Comment by AnatolyKulakov** [comment]
@unchase , спасибо большое. В этом релизе ты закрыл кучу очень неприятных багов :pray:

**Comment by unchase** [comment]
> @unchase , спасибо большое. В этом релизе ты закрыл кучу очень неприятных багов 🙏

Каждый поддерживает сообщество как может)

**Comment by pfedotovsky** [comment]
@AnatolyKulakov отправил версию 2.2.0 в магазины. Версия под Android должна быть доступа через пару дней, но возможны задержки из-за коронавируса. Версия под iOS должна быть доступна через пару часов.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/13116698/78505038-49bb9600-7779-11ea-82c4-192571d086a7.png">

Всем ошибкам, поправленным в этом релизе, проставил Milestone https://github.com/DotNetRu/App/milestone/4

СС @unchase

**Comment by AnatolyKulakov** [comment]
Проверю, как только будет доступна

**Comment by AnatolyKulakov** [comment]
Отличная работа :+1:
