### ISSUE TITLE
Оптимизировать пустое место на вкладке Speakers

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#34]
На вкладке Speakers слишком много пустого места.

Необходимо увеличить фотографию Докладчика и у уменьшить неиспользуемое пространство. Прекрасным примером является VK клиент, вкладка Friends. Необходимо максимально скопировать его стиль списка.

**Comment by unchase** [comment]
Задача актуальна?

**Comment by AnatolyKulakov** [comment]
Всё скопировали с VK.
