### ISSUE TITLE
Добавить Друзей на страницу с Митапами

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#36]
На вкладке Meetups необходимо добавить секцию Friends (Друзья) и сделать ссылки от туда на страницу Sponsor Details.

**Comment by AnatolyKulakov** [comment]
Всё верно, именно это и хотелось. Только наверное можно текстовые имена компаний опустить. Обычно по логотипу понятно кто это.

**Comment by vadlit** [comment]
https://github.com/DotNetRu/App/pull/217

**Comment by vadlit** [comment]
Новый PR - https://github.com/DotNetRu/App/pull/222

**Comment by unchase** [comment]
Issue можно закрывать. Или в рамках задачи нужно сделать что-то еще?

**Comment by AnatolyKulakov** [comment]
Да, можно закрывать
