### ISSUE TITLE
В списке митапов время всегда All Day

### ISSUE THREAD

**Issue by YuliaFast** [DotNetRu/App#38]
![screenshot_20171026-172454](https://user-images.githubusercontent.com/12753429/32058720-0f64a1ce-ba73-11e7-9cf4-208c217b154e.png)

**Comment by pfedotovsky** [comment]
@AnatolyKulakov как обсуждали, All day сейчас нормально, пока нету данных о времени встреч в Audit

**Comment by AnatolyKulakov** [comment]
Да, я сейчас добавляю время в Аудит. Скоро будет. Следить можно в DotNetRu/Audit#13

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , добавил Время в Аудит
