### ISSUE TITLE
Пытаюсь "поделиться" с главного экрана, а там пусто

### ISSUE THREAD

**Issue by YuliaFast** [DotNetRu/App#39]
Хотелось делиться не только главным экраном, но и митапами или спикерами. И в тексте должно быть не только "#DotNetRu"

**Comment by YuliaFast** [comment]
"Делиться" в случае митапа - ссылкой на его описание в timepad. В случае доклада - на видео на youtube. Про спикера не знаю, либо его контактами, либо не нужна там такая кнопка.
А на главном экране наверное такая кнопка не нужна

**Comment by pfedotovsky** [comment]
@YuliaFast сделаем "поделиться" для митапа и доклада.
@AnatolyKulakov в Audit модели для митапа нужна ссылка на timepad, или любой другой ShareURL

**Comment by unchase** [comment]
Чем в итоге закончилось?

**Comment by AnatolyKulakov** [comment]
По-факту сейчас кнопка "Поделиться" осталась только в Докладах. И она составляет текст со ссылкой на YouTube.
С остальных мест делиться нельзя.
Кажется, что без переноса Энциклопедии на сайт лучше не сделать. Пусть пока останется так.
