### ISSUE TITLE
Хочется получать нотификации о митапах

### ISSUE THREAD

**Issue by YuliaFast** [DotNetRu/App#41]
Было бы круто подписаться на уведомления о новых митапах в конкретном городе. 
В перспективе регистрироваться прям через приложение, тут надо разбираться с таймпадом

**Comment by AnatolyKulakov** [comment]
Есть уже отдельные таски на это:

- #6 Добавить поддержку multi-tenant режима
- #11 Добавить Push-уведомления
- #27 Добавить возможность регистрации на встречу

Закрываю, как дубликат
