### ISSUE TITLE
Тёмное гамбургер-меню на тёмном фоне

### ISSUE THREAD

**Issue by Kseniya921** [DotNetRu/App#49]
Плохо видно иконку меню, лучше сделать её белой. 
![black_menu](https://user-images.githubusercontent.com/33512661/32604657-794ca4e6-c55f-11e7-8aa7-5c28167c3f6b.jpg)

**Comment by pfedotovsky** [comment]
Решили передать меню на tab bar, поэтому issue уже неактуальна.

**Comment by AnatolyKulakov** [comment]
@pfedotovsky добавь сюда ссылку на новую таску про ta bbar
