### ISSUE TITLE
Добавить страницу «About DotNetRu» («О DotNetRu»)

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#5]
Необходимо добавить отдельную страницу с описанием нашего сообщества.

Текст страницы можно взять из описания [DotNetRu в wiki](https://github.com/AnatolyKulakov/SpbDotNet/wiki).

Сделать банер из логотипа
Забить ссылки на все сообщества из [DotNetRu в wiki](https://github.com/AnatolyKulakov/SpbDotNet/wiki)

- [x] Убрать верхний регистр в тексте "About DotNetRu"
- [x] Сразу после описания сделать красивую кнопку "Друзья" и перенести за неё страницу Friends. С главной панели друзей надо убрать. Смотрится слишком навязчиво.
- [x] Все пункты кроме "Сделано командой DotNetRu..." убрать на отдельную страницу ("Open Source"?), а здесь оставить лишь ссылку на неё.
- [x] Нажатие на "Правила использования" и "Конфидециальность" роняют приложение. Так не надо.
- [x] Добавить пункт "Сообщить об ошибке" со ссылкой на [Issue Tracker](https://github.com/DotNetRu/App/issues)
- [x] Добавить секцию "Наши сообщества" с перечислением всех (DotNetRu, Санк-Петербург, Москва, Саратов, Красноярск). Для каждого сообщества должен быть указан логотип. При клике на сообщество отправлять их на [соответствующую страницу во вконтактике](https://github.com/AnatolyKulakov/SpbDotNet/wiki).

**Comment by AnatolyKulakov** [comment]
Обновил на основании версии 1.0.0.71

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , закрываем?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov еще нет, не все сделано
