### ISSUE TITLE
Пустое место сверху в основном меню 

### ISSUE THREAD

**Issue by Kseniya921** [DotNetRu/App#50]
Нужно вставить логотип сверху или заполнить чем-то пространство. 
![main screen](https://user-images.githubusercontent.com/33512661/32604906-6e5e9aa2-c560-11e7-9261-220e624815ca.jpg)

**Comment by pfedotovsky** [comment]
@AnatolyKulakov предлагаю меню в Android сделать таким же, как на iOS (tab bar). Что думаешь?
В последнее время есть тренд перехода с hamburger menu (как сейчас) на tab bar (иконки меню снизу) - например, VK, YouTube

**Comment by pfedotovsky** [comment]
Решили поменять меню на tab bar
