### ISSUE TITLE
Страница с конкретным митапом

### ISSUE THREAD

**Issue by Piteryo** [DotNetRu/App#53]
![image](https://user-images.githubusercontent.com/4750178/32721556-eb65d848-c877-11e7-9432-953c185be3fa.png)
Нужно поместить заголовок встречи наверх, вместо слова Митап

**Comment by pfedotovsky** [comment]
@AnatolyKulakov делаем?

**Comment by AnatolyKulakov** [comment]
Да. Слово "Митап" вообще не несёт какой-то смысловой нагрузки. Его можно вообще выкинуть. А название встречи это важно.
