### ISSUE TITLE
Объединение моделей

### ISSUE THREAD

**Issue by bruce-willis** [DotNetRu/App#54]
В данный момент на каждую сущность существуют две модели, описывающие её. Например для Meetup - [MeetupModel](https://github.com/DotNetRu/App/blob/develop/DotNetRu.DataStore.Audit/Models/MeetupModel.cs) и [MeetupEntity](https://github.com/DotNetRu/App/blob/develop/DotNetRu.DataStore.Audit/Entities/MeetupEntity.cs). Это обусловлено тем, что приложение для работы использует MeetupModel, а данные хранятся в формате MeetupEntity. 
В связи с этим при запуске необходимо вначале распарсить xml-ки в Entity, и затем, с помощью Extension методов (например [MeetupExtension](https://github.com/DotNetRu/App/blob/develop/DotNetRu.DataStore.Audit/Extensions/MeetupEntityExtensions.cs)), преобразовать их в Models.
Считаю, что целесообразно задуматься об **объедининии** этих моделей

**Comment by pfedotovsky** [comment]
Нет, это две разные модели для разных целей. Entity описывает данные так, как в базе, Model так, как нужно приложению.
