### ISSUE TITLE
UI доработки после второго beta тестирования

### ISSUE THREAD

**Issue by pfedotovsky** [DotNetRu/App#59]
## Вкладка Speaker Info

- [x] Изменить заголовок вкладки на "Speaker" (Лектор)
- [x] Отсортировать Сессии по дате выступления (сначало старые, в конце новые)
- [x] Не показывать в Сессиях имя спикера рядом с докладом. Мы и так на странице спикера, там других быть не может
- [x] В Сессиях, рядом с докладом вместо фотографии спикера отображать логотип сообщества в рамках которого было выступление. Фотография спикера слишком избыточна здесь.

## Вкладка Meetups

- [x] Сейчас начинает что-то обновлять при протаскивании ленты вниз. Не надо делать pull to refresh
- [x] Переименовать русский вариант во "Встречи"
- [x] Месяца в русской версии пишутся с маленькой буквы (в английской нормально). Должны всегда писаться с большой.

## Вкладка Meetup

- [x] Доклады должны быть перечислены в порядке, задонном в Audit'е
- [x] Здесь доклады называются Taks, если зайти через митапы, то там будут Sessions. Надо определиться
- [x] Сделать отображение нескольких фотографий докладчиков

## Вкладка Friends

- [x] Переименовать русскую версию в "Друзья"
- [x] Отсортировать по количеству проведённых встреч. Фирмы, принявшие больше всех митапов, должны быть выше
- [x] Поместить на самый верх, независимо от сортировки наших _лучших друзей_: DotNext, JetBrains (пока хардкодом, никакого формального признака нет)

**Comment by AnatolyKulakov** [comment]
> Отображение нескольких фотографий докладчиков

У докладчика может быть только одна фотография. Ты про что?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov вопрос в том, как отображать фотографии докладчиков для доклада, если их несколько.

Сейчас просто берется фотография рандомного докладчика.

[talks](https://photos.app.goo.gl/bO9LYw3h927wey9q1)

**Comment by AnatolyKulakov** [comment]
Рандом в данном случае это не справедливо.

Сейчас можно показывать системную иконку на которой будет изображено множество участников. Что-то типа:
![multiple-users-silhouette](https://user-images.githubusercontent.com/11032050/33282057-73baea9e-d3b8-11e7-8f76-a1fdc033addb.png)

В будущем конечно хочется научиться манипулировать с иконками и делать мозайку из реальных участников.

**Comment by AnatolyKulakov** [comment]
Обновил в соответствии с версией 1.0.0.71
Вернул pull to refresh. Не ущёл.
