### ISSUE TITLE
Отформатировать Twitter

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#63]
Сейчас лента новостей по внешнему виду сильно расходится с [версией на сайте Твитера](https://twitter.com/dotnetru). Необходимо привести их в максимально похожий вид.

Например:

- [x] Необходимо декодировать HTML форматирование (см. `Span<T>`)
- [x] В приложении многие сообщения представлены не полностью и обрезаются тремя точками. Необходимо показывать сообщение целиком.
- [x] Ссылки в web версии представлены в виде правильных адресов, в приложении все ссылки ведут через сайт "t.co". Необходимо чтобы ссылка отображалась в виде оригинального текста.
- [x] В оригинальной ленте всегда почти всегда есть Twitter Card: картинка, текст описания и т.д. В приложении почти все сообщения ограничиваются текстовой версией. Желательно также отображать Twitter Card и полноразмерные картинки.
- [x] У каждого твита должна быть панель с количеством лайков, ретвитов и комментариев, показывающих популярность сообщения.
- [x] В приложении у каждого твита есть надпись `DotNetRu` вверху и `@DotNetRu` внизу. Это избыточно. Достаточно одной.
- [x] Ретвиты в приложении помечаются специальным префиксов (`RT...`). Не надо префикса.

![news](https://user-images.githubusercontent.com/11032050/33457735-90cbf708-d634-11e7-8f55-7286754ae2d1.PNG)

**Comment by AnatolyKulakov** [comment]
Похоже на то, что нам нужно:
https://www.thewissen.io/xamarin-forms-ui-twitter/

**Comment by AnatolyKulakov** [comment]
Сейчас (86) лента выглядит намного лучше. Но отличия всё ещё существенные.
@pfedotovsky , сможем исправить всё до первого релиза?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov думаю, да. @Piteryo какой сейчас статус?

**Comment by Piteryo** [comment]
@pfedotovsky В процессе, через час, думаю, залью версию немного лучше отформатированную. Пока что осталось пофиксить ссылки и проверить HTML

**Comment by Piteryo** [comment]
В принципе почти готово, но возник такой вопрос, не стоит ли при ретвите указывать как-то откуда ретвит? А то сейчас стоит картинка хабра, но пользователь дотнетру, это как-то странно. Какие предложения как это отобразить?

**Comment by Piteryo** [comment]
![image](https://user-images.githubusercontent.com/4750178/35474786-219393f8-03a4-11e8-972f-fe692e58ddfd.png)

**Comment by AnatolyKulakov** [comment]
@Piteryo , надо ориентироваться на Web версию. Т.е. при ретвите должны стоять имена Хабры. И (в отличии от web версии) думаю не надо добавлять надпись
> 🔁  DotNetRu ретвитнул(а)
И так понятно, что больше некому ретвитнуть.

Поэтому при ретвите указывай просто имена источника. При этом упоминания DotNetRu в таком твите не будет совсем.

**Comment by Piteryo** [comment]
@AnatolyKulakov то есть в нашем варианте грубо говоря достаточно будет DotNetRu поменять на Хабрахабр? Но тогда ведь не будет понятно, что это ретвит (хотя надо ли об этом кому-то знать)

**Comment by AnatolyKulakov** [comment]
Да, надо просто поменять. Я не вижу никакой ценности в информации о том, что это ретвит. Для нас "ретвит" это просто признак, что новость интересная и нам надо показать её в ленте. Что мы собственно и сделаем.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov можно смотреть, 95 версия

**Comment by AnatolyKulakov** [comment]
@Piteryo отличная работа 👍 
Осталась пара моментов:
- Нет поддержки Twitter Card и Open Graph (см. твит про запуск сайта или любой youtube). Если это сложно, то можно отложить.
- Сейчас 2 раза дублируется имя акаута (`spbdotnet spbdotnet`). И эти имена часто не влазят (переносятся, сокращаются). Давайте не будем писать Твитер имя вообще, а заменим их 1 раз на Твиттер Название аккаунта (должно быть `SpbDotNet Community`)? Так должно всем хватить места.

**Comment by Piteryo** [comment]
@AnatolyKulakov то есть такие твиты надо отображать грубо говоря с картинкой-ссылкой? Это все отличие?

**Comment by AnatolyKulakov** [comment]
@Piteryo , давай пофиксим `name` → `ttile`. А OG перенесём на следующую итерацию?

**Comment by AnatolyKulakov** [comment]
Хотя нет. Давай обе задачи перенесём. Первая будет отличной `first issue`

**Comment by AnatolyKulakov** [comment]
Разбил на #121 и #122
