### ISSUE TITLE
Запретить добавлять прошедшие события в календарь

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#8]
Сейчас пользователь может открыть прошедшее событие (*Event*) и добавить напоминание о нём в системный календарь.

Необходимо запретить ему добавлять прошедшие события в календарь. У пользователя не должно создаваться ложных ожиданий, если он случайно не обратил внимание на дату.

**Comment by pfedotovsky** [comment]
Поскольку сейчас все события, отображаемые в приложении, прошедшие, то сама возможность добавления в календарь временно отключена. Добавление событий будет реализовано в milestone "Новости".

**Comment by AnatolyKulakov** [comment]
Создал #44
