### ISSUE TITLE
UI доработки после третьего beta тестирования

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#82]
## Вкладка Speaker

- [x] Переименовать везде "Speaker" в русском варианте с "Лектора" на "Докладчика"
- [x] В списке докладов, доклады с длинным названием обрезаются. Необходимо, чтобы доклад влезал с любым размером названия.
![image-1](https://user-images.githubusercontent.com/11032050/34612183-a4c6fa84-f239-11e7-8c1f-46905be5a06c.jpg)

## Вкладка Meetup

- [x] Список докладов должен быть с именами спикеров в формате: `Сергей Лёвкин «Технологии Microsoft для актуальных трендов»`
- [x] Добавить имя Встречи и дату проведения Встречи в формате: `Встреча SarDotNet №1 состоялась 30 сентября 2017 г.`. Можно первым пунктом в секцию Venue

## Вкладка Talk

- [x] Перевести текст "Presentation Slides" в русском варианте как "Слайды"
- [x] Перевести текст "Talk Recording" в русском варианте как "Видео"

 ## Вкладка About

- [x] Отсортировать список сообществ по мере их появления, [например как в wiki](https://github.com/AnatolyKulakov/SpbDotNet/wiki)
- [x] Сейчас верхний логотип DotNetRu выглядит очень пикселизированно. Якобы фотография в очень низком качестве. Необходимо использовать [логотип подобающего качества](https://github.com/AnatolyKulakov/SpbDotNet/tree/master/Swag/dotnetru-squared-logo)
- [x] Убрать верхний регистр в тексте "About DotNetRu"

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , закрываем?

**Comment by pfedotovsky** [comment]
@AnatolyKulakov да. Я ждал пока новая версия выложится в магазины.
