### ISSUE TITLE
Неверное поведение кнопки Back в Twitter'е

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#83]
Если пользователь переходит на YouTube из карточки конкретного доклада, то _back_ возвращает его обратно в приложение. Если же он это делает из первого раздела Social и переходит в приложение Twitter, то _back_ работает внутри Твиттера и не возвращает пользователя обратно в приложение.

Сценарий воспроизведения:

-  закрыл все приложения;
- открыл Твиттер;
- тапнул на какой-нибудь твит;
- тапнул _back_. Вернулся в ленту твиттера;
- перешёл на home screen и запустил DotNetRu App;
- дождался загрузки ленты новостей;
- тапнул на новость;
- нажал back - и оказался в приложении Twitter, а не в DotNetRu App.

Если не запускать Твиттер первым или если не тапать по конкретным твитам в твиттере, а просто покрутить ленту, то App ведёт себя правильно т.е. _back_ возвращает в приложение.

Дополнительные подробности можно выяснить у @ilabutin

**Comment by bruce-willis** [comment]
@AnatolyKulakov @ilabutin такое поведение связано не с нашим приложением, а с приложением Twitter'a, а именно с тем как оно обрабатывает Intent'ы (через них осуществляется переход в приложение твиттера) - скорей всего он добавляет просто ещё один фрагмент в fragment manager, который уже и управляет кнопкой `back`. [Вот например](https://imgur.com/a/9D9Ue) абсолютно такое же поведение в приложении Tjournal. Боюсь, что мы ничего не сможем с этим поделать. Кроме того, нажатие `back` повторно всё же возвращает обратно в приложение.

**Comment by AnatolyKulakov** [comment]
Ясно, тогда закрываем
