### ISSUE TITLE
Вытаскивать меню с левой стороны экрана

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#9]
Сейчас основное меню приложения появляется только по нажатию кнопки в левом-верхнем углу.

Необходимо отображать меню также при проведении пальцем в горизонтальном направлении от левой кромки экрана вправо (Swipe). При обратном движении меню должно закрываться.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov Это на Windows 10? На Android все работает как надо.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AnatolyKulakov** [comment]
Да, тестировал на Windows Mobile 10
Тогда откладываем этот баг. Вернёмся к нему, если решим поддерживать Windows.

**Comment by AnatolyKulakov** [comment]
Мы отказались от подобного меню
