### ISSUE TITLE
Сломалась фотография докладчика

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#90]
На станице Speaker, фотография спикера вверху теперь показывает только макушку человека, раньше влезала голова полностью.

Cломался эффект увеличения фотографии (слишком сильно увеличивает) при потягивании страницы вниз. Раньше увеличение было небольшим и приглядным.

Только что проверил, в 76 версии фотография работает правильно. В 81 и 82 уже сломана. Необходимо вернуть поведение фотографии из 76 версии.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov поправлено в 88 версии.

**Comment by AnatolyKulakov** [comment]
Fixed
