### ISSUE TITLE
Разделить Дату и Адрес проведения мероприятия

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#91]
Сейчас на вкладке Meetup, в секции "Место проведения" Дата и Адрес отображаются одним элементом. Сие не очень красиво.

Необходимо отображать эти поля, как разные элементы секции. Как на рисунке:

![58a25149-e741-4e36-9f9c-255da68ab05d](https://user-images.githubusercontent.com/11032050/35172148-87ffb0a0-fd77-11e7-8912-f5e0f49e0889.jpg)

**Comment by bruce-willis** [comment]
@AnatolyKulakov 
![image](https://user-images.githubusercontent.com/21131904/35301772-818b5930-009d-11e8-9707-4d165ced3308.png)

**Comment by pfedotovsky** [comment]
@AnatolyKulakov готово, можно проверять

**Comment by AnatolyKulakov** [comment]
Теперь хорошо
