### ISSUE TITLE
Перенести логотип DotNetRu наверх

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#92]
Сейчас на вкладке About упоминание о DotNetRu находится в секции "Наши сообщества". Это не корректно, ибо DotNetRu не является сообществом.

Необходимо:

- убрать упоминание DotNetRu из секции сообществ;
- добавить логотип DotNetRu в секцию "О DotNetRu" с обтеканием текста по правому краю и сделать эту картинку ссылкой на сайт http://dotnet.ru/;
- в секции "О DotNetRu" сделать текст "Всероссийское .NET сообщество DotNetRu" ссылкой на сайт http://dotnet.ru/ с визуальным отличием от дальнейшего текста

**Comment by pfedotovsky** [comment]
@AnatolyKulakov ссылку в тексте сделать непросто. Предлагаю сделать только картинку и по клику переход на сайт. ОК?

**Comment by AnatolyKulakov** [comment]
@pfedotovsky , да, давай тогда без ссылки

**Comment by pfedotovsky** [comment]
@AnatolyKulakov готово, можно проверять

**Comment by AnatolyKulakov** [comment]
1. А нельзя сделать обтекание текстом правильное? Чтобы картинка занимала только левую верхнюю часть, а не всю левую и текст, соответственно должен быть справа-снизу, а не справа?

1. Давай сделаем на картинке ссылку на http://dotnet.ru/ . На момент релиза сайт должен быть уже запущен.

@pfedotovsky

**Comment by pfedotovsky** [comment]
@AnatolyKulakov @yurybelousov @piteryo посмотрите?

**Comment by bruce-willis** [comment]
@AnatolyKulakov @pfedotovsky [по всей видимости](https://stackoverflow.com/questions/40718281/how-do-you-format-a-text-around-an-image), это невозможно сделать средствами xamarin.forms без залезания вглубь платформ. В качестве промежуточного решения можно разбить весь текст на две части: чтобы одна часть была справа, а вторая — ниже.
Вот как это выглядит
![image](https://user-images.githubusercontent.com/21131904/35412848-a21cb27e-022e-11e8-8801-2e8df307d4e7.png)

**Comment by AnatolyKulakov** [comment]
@bruce-willis , отличное решение 👍 . Давай разобьём!

**Comment by pfedotovsky** [comment]
@AnatolyKulakov можно смотреть, версия 91

**Comment by AnatolyKulakov** [comment]
Всё хорошо, но появился артифакт #112
