### ISSUE TITLE
Добавить дату проведения встречи на вкладку Meetups

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#93]
Сейчас на вкладке Meetups под названием Встречи всегда отображается дата "Весь день". Если перейти непосредственно на страницу самой встречи (Meetup), то в секции "Место проведения" можно увидеть правильную дату проведения.

Необходимо отображать правильную дату проведения Встречи в списке встреч на странице Meetups.

**Comment by pfedotovsky** [comment]
@AnatolyKulakov готово, можно проверять

**Comment by AnatolyKulakov** [comment]
Сейчас хорошо
