### ISSUE TITLE
Наполнить README файл

### ISSUE THREAD

**Issue by AnatolyKulakov** [DotNetRu/App#95]
Необходимо наполнить README.md файл полезной информацией. Всё описание должно быть на Великом и могучем русском языке. Как то:

- описание приложения со снимками экранов (как в store)
- ссылки на скачивания приложения из сторов
- список поддерживаемых ОС (с версиями)
- описание как собрать приложение в локальном окружении (установка и настройка зависимостей)
- как сделать pull request (есть подробные инструкции от GitHub)
- как оформить баг (вопрос, фичу)
- ссылку на Up for grabs таски

**Comment by bruce-willis** [comment]
Можно смотреть в ветке [`feature/documentation`](https://github.com/DotNetRu/App/tree/feature/documentation)

**Comment by AnatolyKulakov** [comment]
@bruce-willis , ссылки на скачивания можно сделать стандартным родными для маркетов (по дизайну) кнопками?

**Comment by bruce-willis** [comment]
@AnatolyKulakov 
![image](https://user-images.githubusercontent.com/21131904/35536010-95f5c212-0556-11e8-8ed3-7d17b2115a40.png)
